import { NotImplementedError } from '../exceptions'

export const validateResponse = async (data: any): Promise<IResponse> => {
  throw new NotImplementedError('Validate response')
}
